# Generated by Django 5.2.5 on 2025-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apartment_number', models.IntegerField()),
                ('zip_code', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateTimeField()),
                ('party_affiliation', models.CharField(max_length=2)),
                ('precinct_number', models.IntegerField()),
                ('v20state', models.TextField()),
                ('v21town', models.TextField()),
                ('v21primary', models.TextField()),
                ('v22general', models.TextField()),
                ('v23town', models.TextField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
