# Generated by Django 5.2.5 on 2025-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(),
        ),
    ]
