# Generated by Django 5.2.5 on 2025-10-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(),
        ),
    ]
