# Generated by Django 5.2.5 on 2025-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='audio_file',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(),
        ),
    ]
