# Generated by Django 5.2.5 on 2025-11-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_file_song_audio_file_song_audio_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_by',
            new_name='commenter',
        ),
    ]
