# Generated by Django 5.2.5 on 2025-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_comment_text_alter_song_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
