# Generated by Django 5.2.5 on 2025-11-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_song_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='uploader',
            new_name='profile',
        ),
    ]
