# Generated by Django 5.2.5 on 2025-12-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_uploader_song_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='profile',
        ),
    ]
