# Generated by Django 5.2.5 on 2025-12-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_commenter_comment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liked_by',
            new_name='profile',
        ),
    ]
